apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  labels:
    app: pgadmin
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password
  PGADMIN_DEFAULT_EMAIL: example@gmail.com
  PGADMIN_DEFAULT_PASSWORD: password