apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      volumes:
      - name: shared-volume-between-initcontainer-and-container
        emptyDir: {}
      initContainers:
      - name: busybox
        image: busybox
        volumeMounts:
        - name: shared-volume-between-initcontainer-and-container
          mountPath: /data
        command: ["/bin/sh"]
        args: ["-c", "echo '<h1>Hello, my name is Nikhil Sharma</h1>' > /data/index.html"]

      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-volume-between-initcontainer-and-container
          mountPath: /usr/share/nginx/html
--- 
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    run: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80