apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  initContainers:
  - name: busybox
    image: busybox
    volumeMounts:
    - mountPath: /data
      name: host-path-volume
    command: ["/bin/sh"]
    args: ["-c", "echo '<h1>Hello Kubernetes</h1>' > /data/index.html"]
  containers:
  - image: nginx:latest
    name: test-container
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: host-path-volume
    ports:
    - containerPort: 80
  volumes:
  - name: host-path-volume
    hostPath:
      path: /data
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    run: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
